osx_image: xcode8.2
langauge: objective-c
cache:
  - bundler
  - cocoapds
branches:
  only:
    - develop
    - master
notifications:
  email: false
before_install:
  - gem install bundler
  - bundle install
script:
  - bundle exec fastlane bonjour
