lane :bonjour do

  scan(
  code_coverage: true
  )
  xcov

end


lane :deploy do

  if git_branch() == "master"
    version = get_version_number()

    set_github_release(
      repository_name: "Mohsan1995/fastlane-demo-moc2",
      name: version,
      tag_name: "v#{version}",
      api_token: ENV["GITHUB_TOKEN"],
      description: changelog_from_git_commits(),
      commitish: "master"
    )
  end

end
